Ot90 689
alkemyTech/OT-90-server pull request #14
Opened 2021-10-27 14:51 UTC by benjaminPla

- Create getAll for contacts endpoint
- Fix misspelling error on modules/contacts (deteledAt-> deletedAt)

Tested on postman locally:
<img width="1280" alt="Screen Shot 2021-10-27 at 11 47 28" src="https://user-images.githubusercontent.com/85419447/139090051-107f7d91-0597-448d-ac61-d8e8721b5429.png">

JSON link to my Alkemy postman: https://www.getpostman.com/collections/64331e0fdefdfc5d9295

_It would be nice to talk about where to write the lines of code refered to routes on app.js_

2021-10-27 15:21 UTC, dvelezroman approved these changes

2021-10-27 15:21 UTC, dvelezroman commented on models/contacts.js
> +    deletedAt: DataTypes.STRING
excelente... good catch

2021-10-27 20:09 UTC, andresmonsa requested changes

2021-10-27 20:09 UTC, andresmonsa commented on app.js
> +app.use('/contacts', contactsNetwork)
route in routes/index,js  instead app.js

2021-10-27 23:11 UTC, benjaminPla commented on app.js
> +app.use('/contacts', contactsNetwork)
transferred and checked! 

<img width="1280" alt="Screen Shot 2021-10-27 at 20 07 45" src="https://user-images.githubusercontent.com/85419447/139160426-354d1491-cfbe-481b-bd20-2890faae30d6.png">

2021-10-27 23:25 UTC, verteramofederico approved these changes

2021-10-27 23:26 UTC, Francisco-Merchan approved these changes

2021-10-28 11:24 UTC, andresmonsa approved these changes

2021-10-28 11:26 UTC, merged