Ot90 668
alkemyTech/OT-90-server pull request #19
Opened 2021-10-28 12:05 UTC by andresmonsa

creating and adding middleware to verify user role to GET users

2021-10-28 14:11 UTC, dvelezroman requested changes

2021-10-28 14:11 UTC, dvelezroman commented on middleware/index.js
> +      next()
excellent

2021-10-28 14:11 UTC, dvelezroman commented on middleware/index.js
> +    if (roleId === '1') {
aqui el role es integer ... no string ...

2021-10-28 14:11 UTC, dvelezroman commented on middleware/index.js
> +    if (roleId === '1') {
debe primero hacer un request a la tabla roles.. para verificar que rol es admin ? ... y con eso comparar el rol enviado en los parametros de la request ?

2021-10-28 14:37 UTC, andresmonsa commented on middleware/index.js
> +    if (roleId === '1') {
Fixed!

2021-10-28 16:27 UTC, jpuery71292 commented
Por lo que vi no genera conflicto con el código
usa la petición al middleware correctamente

2021-10-28 16:28 UTC, jpuery71292 approved these changes

2021-10-28 17:53 UTC, benjaminPla approved these changes

2021-10-28 17:53 UTC, benjaminPla commented on middleware/index.js
> +    const roleId = req.header('roleId')
maybe we can use destructurin:
const [roleId ] = req.header

2021-10-28 18:37 UTC, andresmonsa commented on middleware/index.js
> +    const roleId = req.header('roleId')
![image](https://user-images.githubusercontent.com/73470251/139315550-1ecec92d-4707-4571-8bdc-0366e0260b11.png)

doesn´t work this way

2021-10-28 19:16 UTC, benjaminPla commented on middleware/index.js
> +    const roleId = req.header('roleId')
try using [] not {}

2021-10-28 19:26 UTC, verteramofederico commented on middleware/index.js
> +    const roleId = req.header('roleId')
el nombre index para el middleware es como para que contenga todos los futuros que haya en la app? si no quizas seria mejor renombrarlo mas especifico. 
Me pregunto si esta bien que la función del middleware sea asíncrona? Siendo que esta chequeando si el usuario es o no adm, no debería detener ejecución hasta resolver la respuesta?

2021-10-28 19:38 UTC, andresmonsa commented on middleware/index.js
> +    const roleId = req.header('roleId')
FIXED!
The correct way is : 
    const { roleid } = req.headers

2021-10-29 11:23 UTC, andresmonsa commented on middleware/index.js
> +    const roleId = req.header('roleId')
>> el nombre index para el middleware es como para que contenga todos los futuros que haya en la app? si no quizas seria mejor renombrarlo mas especifico.
<<
Se puede hacer  en archivos separados si lo queremos hacer así.

>> Me pregunto si esta bien que la función del middleware sea asíncrona? Siendo que esta chequeando si el usuario es o no adm, no debería detener ejecución hasta resolver la respuesta?
<<
Hay una consulta a la base de datos, por lo que tiene que ser asíncrono.
Sin el await, la ejecución pasa de la linea 8 a la 9 antes de que termine la query y nunca se cumple la condición.
![image](https://user-images.githubusercontent.com/73470251/139426433-16ebbf46-feda-46a9-8518-1e873c2ead86.png)

2021-10-29 12:53 UTC, verteramofederico commented on middleware/index.js
> +    const roleId = req.header('roleId')
> > > el nombre index para el middleware es como para que contenga todos los futuros que haya en la app? si no quizas seria mejor renombrarlo mas especifico.
> > > <<
> > > Se puede hacer  en archivos separados si lo queremos hacer así.
> 
> > > Me pregunto si esta bien que la función del middleware sea asíncrona? Siendo que esta chequeando si el usuario es o no adm, no debería detener ejecución hasta resolver la respuesta?
> > > <<
> > > Hay una consulta a la base de datos, por lo que tiene que ser asíncrono.
> > > Sin el await, la ejecución pasa de la linea 8 a la 9 antes de que termine la query y nunca se cumple la condición.
> > > ![image](https://user-images.githubusercontent.com/73470251/139426433-16ebbf46-feda-46a9-8518-1e873c2ead86.png)

ahi va gracias!!!

2021-10-29 12:54 UTC, verteramofederico approved these changes

2021-10-29 12:56 UTC, dvelezroman commented on middleware/index.js
> +    const roleId = req.header('roleId')
should be 
`if (role.name.toLowercase() === 'admin')`

2021-10-29 12:59 UTC, benjaminPla commented on middleware/index.js
> +    const roleId = req.header('roleId')
maybe add a trim() too

2021-10-29 13:08 UTC, dvelezroman approved these changes

2021-10-29 13:11 UTC, andresmonsa commented on middleware/index.js
> +    const roleId = req.header('roleId')
Done!

2021-10-29 13:14 UTC, dvelezroman approved these changes

2021-10-29 13:14 UTC, dvelezroman commented on middleware/index.js
> +      if (role.name.toLowerCase().trim() === 'admin') {
good

2021-10-29 13:24 UTC, merged