OT90-649
alkemyTech/OT-90-server pull request #26
Opened 2021-10-31 21:05 UTC by benjaminPla

COMO: usuario
QUIERO: estar autenticado en la plataforma
PARA: poder acceder a todos sus servicios.

Criterios de aceptación: Cuando el usuario se autentica, el servidor deberá generar un JSON Web Token con los datos del usuario, y devolver el mismo en la respuesta.
Para validar que el usuario está autenticado, el servidor deberá desencriptar este token, obteniéndolo del encabezado Authorization de la petición recibida.
Librería sugerida: https://www.npmjs.com/package/jsonwebtoken

--

1. Add jwt on dependencies
2. Add jwt logic on user/register endpoint (response can be changed)
3. Add jwt (check 'missing' and 'invalid') middleware (tested on contacts endpoint)

_The only way to get a correct a funcionability is to add 'TOKEN=alkemy' on .env file._

2021-11-01 18:46 UTC, jpuery71292 approved these changes
No conocía el proceso. justo hablamos
Tener en cuenta que hay otras ramas que tocan el package.json
así coordinar para el merge

2021-11-01 19:22 UTC, dvelezroman requested changes

2021-11-01 19:22 UTC, dvelezroman commented on components/user/controller.js
> +    return jwt.sign(userData, process.env.TOKEN)
los datos del user y el token .. se deben enviar al front ....  el json de la respuesta puede proponerse asi : 
`response = {
    status: true,
    data: {
      token: 'sdsd',
      user: {
       ....userData
     }
}`

2021-11-01 19:22 UTC, dvelezroman commented on components/user/controller.js
> +    return jwt.sign(userData, process.env.TOKEN)
Que opinan ?

2021-11-01 19:22 UTC, dvelezroman commented on middleware/index.js
> +  invalidToken: (req, res, next) => {
cambiemos el nomrbe del metodo.. quizas ... verifyToken ?

2021-11-01 19:22 UTC, dvelezroman commented on package.json
> +    "nodemon": "^2.0.12",
esto no ....

2021-11-01 19:22 UTC, dvelezroman commented on package.json
> +    "jsonwebtoken": "^8.5.1",
quitar caret ^

2021-11-01 19:22 UTC, dvelezroman commented on routes/index.js
> +router.use('/contacts', invalidToken, contactsNetwork)
como el comment de arriba... cambiar nombre al middleware... verifyToken ... quizas

2021-11-01 20:51 UTC, benjaminPla commented on components/user/controller.js
> +    return jwt.sign(userData, process.env.TOKEN)
perfecto, ahora coordinamos una respuesta general, yo personalmente uso 'body' para lo que es string al cliente.

2021-11-02 13:48 UTC, dvelezroman approved these changes

2021-11-02 22:08 UTC, verteramofederico approved these changes

2021-11-02 22:16 UTC, merged