OT90-687
alkemyTech/OT-90-server pull request #3
Opened 2021-10-26 00:10 UTC by benjaminPla

COMO: Usuario administrador
QUIERO: Almacenar los datos al completar el formulario de contacto
PARA: Tener una base de datos de contactos

Criterios de aceptación: Al completar el formulario de contacto, se almacenará en la base de datos. Nombre de tabla: contacts. Contendrá los campos name, phone, email, message, deletedAt (utilizada para soft delete)

---

Steps I took:

1.  git clone
2. add .env
2. npm install --save-dev sequelize-cli
3. npx sequelize-cli model:generate --name Contacts --attributes name:string,phone:string,email:string,message:string,createdAt:string,updatedAt:string,deletedAt:string
4. fix data type from previous step manually, i don't know how to set to date
5. npx sequelize-cli db:migrate
6. npx sequelize-cli seed:generate --name demo-contacts
7. add mock data from https://www.mockaroo.com/
8. locally verify the correct operation of the code

<img width="1280" alt="Screen Shot 2021-10-25 at 21 10 09" src="https://user-images.githubusercontent.com/85419447/138787364-48812797-fa2f-4c53-94e7-773424f27fc2.png">
<img width="1280" alt="Screen Shot 2021-10-25 at 21 10 29" src="https://user-images.githubusercontent.com/85419447/138787379-50b9c871-16be-49cc-b649-e247538f4cb5.png">

2021-10-26 02:21 UTC, dvelezroman requested changes
quitar el archivo package-lock.json del PR...

2021-10-26 16:32 UTC, dvelezroman commented
Por que se modifico el package-lock.json ?

2021-10-27 00:47 UTC, benjaminPla commented
> Por que se modifico el package-lock.json ?

Estoy como LOCO buscando el por que, pude ver que desde mi primer commit se elimino entero el package-lock.json PERO lo raro es que esta dentro del .gitignore, por lo que no entiendo como llego hasta aca.
SIgo buscando caminos para pasar por los Checks y poder mergear,
por favor si alguien sabe o se le ocurre alguna solucion que me avise! :'(

2021-10-27 01:01 UTC, benjaminPla commented on package-lock.json
> +}
Era esto, una simple new line en el final del archivo, SOLUCIONADO!

2021-10-27 03:29 UTC, dvelezroman approved these changes

2021-10-27 10:13 UTC, andresmonsa commented on package-lock.json
> +}
Qué bueno lo pudiste resolver !  Te recomiendo usar Git Lens... te marca los archivos que han sido modificados y te muestra quien hizo el cambio

2021-10-27 10:14 UTC, andresmonsa approved these changes
Costó pero salió jajaja!
:)

2021-10-27 11:32 UTC, verteramofederico approved these changes

2021-10-27 12:13 UTC, jpuery71292 approved these changes
buen trabajo.

2021-10-27 12:14 UTC, merged