Ot90 671
alkemyTech/OT-90-server pull request #30
Opened 2021-11-01 17:29 UTC by verteramofederico

- post News
- express validator to validate existing req.
- isAdmin middleware incorporated
- sintax bug fixed in entries model and migration
- change in Get news
- column type automatic assignment 

COMO: Usuario administradorQUIERO: Crear una novedadPARA: Mantener el contenido actualizado

Criterios de aceptación: POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla entries. Antes de almacenarla, deberá asignarle la columna type con el valor "news".

2021-11-01 20:27 UTC, dvelezroman approved these changes

2021-11-01 20:46 UTC, benjaminPla approved these changes
great!

2021-11-01 20:46 UTC, benjaminPla commented on models/entries.js
> +}
newline

2021-11-01 20:46 UTC, benjaminPla commented on migrations/202110261634-create-entries.js
> +}
newline

2021-11-02 11:21 UTC, marcelonieva7 commented on models/entries.js
> +    timestamps: false
no tiene que estar esta linea para que timestamps sea true por default y asi funcione el soft delete

2021-11-02 11:24 UTC, marcelonieva7 requested changes

2021-11-02 11:24 UTC, marcelonieva7 commented on components/news/network.js
> +  body('name').notEmpty().isLength({ max: 200 }),
la validacion tiene que hacerce con el middleware validation y usando un schema de yup

2021-11-02 14:54 UTC, verteramofederico commented on components/news/network.js
> +  body('name').notEmpty().isLength({ max: 200 }),
incorporado en ultimo commit

2021-11-02 14:54 UTC, verteramofederico commented on models/entries.js
> +    timestamps: false
eliminado en ultimo commit

2021-11-02 22:21 UTC, marcelonieva7 approved these changes

2021-11-02 22:37 UTC, merged