OT90-713
alkemyTech/OT-90-server pull request #31
Opened 2021-11-01 17:46 UTC by andresmonsa

![image](https://user-images.githubusercontent.com/73470251/139716186-3560d8da-c0c8-4280-9f29-b8c6aad2366f.png)

----

![image](https://user-images.githubusercontent.com/73470251/139716326-0aaf037b-89a6-457c-af1e-dec7969e20af.png)

---

![image](https://user-images.githubusercontent.com/73470251/139716346-907d55da-e802-4317-bad1-9dbb13d420a1.png)

2021-11-01 18:23 UTC, jpuery71292 approved these changes
good code

2021-11-01 20:21 UTC, marcelonieva7 requested changes

2021-11-01 20:21 UTC, marcelonieva7 commented on components/categories/network.js
> +router.post('/', validate.validation(categorySchema), async (req, res) => {
Falta la verificación de privilegios administrativos

2021-11-01 20:28 UTC, dvelezroman commented on components/categories/network.js
> +router.post('/', validate.validation(categorySchema), async (req, res) => {
el middleware isAdmin

2021-11-01 20:29 UTC, dvelezroman requested changes
Falta conectar el middleware isAdmin...

2021-11-01 20:46 UTC, andresmonsa commented on components/categories/network.js
> +router.post('/', validate.validation(categorySchema), async (req, res) => {
@marcelonieva7  @dvelezroman  Fixed

2021-11-02 18:50 UTC, marcelonieva7 approved these changes

2021-11-02 22:08 UTC, verteramofederico approved these changes

2021-11-02 22:17 UTC, benjaminPla approved these changes

2021-11-02 22:21 UTC, dvelezroman approved these changes

2021-11-03 10:12 UTC, merged