Create Endpoint - new contact
alkemyTech/OT-90-server pull request #32
Opened 2021-11-01 18:01 UTC by jpuery71292

Endpoint post

create contact
![image](https://user-images.githubusercontent.com/66072856/139718256-afa7fdf1-40fc-4fb8-9759-95d3d7dc0908.png)

validation name and email
![image](https://user-images.githubusercontent.com/66072856/139718347-5f98f26c-325b-4e9a-bc8e-b31e3b6757ae.png)

validation contact = exists
![image](https://user-images.githubusercontent.com/66072856/139718467-51333a75-b661-4695-b59c-2d8494d4355a.png)

2021-11-01 20:29 UTC, dvelezroman requested changes
agregar reviewers

2021-11-02 12:12 UTC, jpuery71292 commented
> agregar reviewers

ahí los agregue Darío, me re olvido de hacerlo

2021-11-02 22:23 UTC, dvelezroman approved these changes
Completar con el formato de los endpoints y middleware y yups

2021-11-02 22:23 UTC, dvelezroman commented on components/contacts/network.js
> +const { body, validationResult } = require('express-validator')
sacar y usar yup

2021-11-03 14:04 UTC, jpuery71292 commented on components/contacts/network.js
> +const { body, validationResult } = require('express-validator')
corregido, y agregue tambien estructura json

2021-11-03 14:06 UTC, andresmonsa approved these changes
Cool!

2021-11-03 14:58 UTC, benjaminPla approved these changes

2021-11-03 21:33 UTC, merged