OT90-641
alkemyTech/OT-90-server pull request #44
Opened 2021-11-04 03:37 UTC by benjaminPla

Endpoint de autenticación
COMO: Usuario
QUIERO: Autenticarme en la pagina
PARA: Tener acceso a ella

Criterios de aceptación: POST /auth/login   Deberá validarse el envío de los campos email y password en la petición, y desencriptar la contraseña para autenticarse

1. Validar email y password en petición
2. Verificar si existe usuario con el email solicitado
3. Si existe, comparar contraseña encriptada con contraseña enviada en petición
4. Devolver al usuario en el caso de que exista y la contraseña sea válida, en el caso de que ocurra un error, devolver {ok: false}

--

1. Create auth endpoint
2. Fix eslint recommendations

_I need to add some middlewares for email and password validation, but i dont know if it is my task_
<img width="1280" alt="Screen Shot 2021-11-04 at 00 31 40" src="https://user-images.githubusercontent.com/85419447/140253922-358138ac-879c-46e1-a88d-65a3a9240ec1.png">
<img width="742" alt="Screen Shot 2021-11-04 at 00 31 45" src="https://user-images.githubusercontent.com/85419447/140253935-2ef233d9-6673-46b7-982d-4f0f61d1353c.png">
<img width="1280" alt="Screen Shot 2021-11-04 at 00 32 15" src="https://user-images.githubusercontent.com/85419447/140253937-29eb5352-1a0d-41f1-a21d-d0e389dacafd.png">
<img width="742" alt="Screen Shot 2021-11-04 at 00 32 18" src="https://user-images.githubusercontent.com/85419447/140253940-56435c22-63a4-43e5-ab18-ad58d9364d3c.png">

2021-11-04 12:53 UTC, dvelezroman requested changes

2021-11-04 12:53 UTC, dvelezroman commented on components/user/network.js
> +      ? res.status(200).json({ success: true, body: 'ok' })
faltaria enviar un JWT token .... para que el cliente lo reciba y lo guarde en el local storage.

2021-11-04 19:30 UTC, benjaminPla commented on components/user/network.js
> +      ? res.status(200).json({ success: true, body: 'ok' })
<img width="832" alt="Screen Shot 2021-11-04 at 16 28 29" src="https://user-images.githubusercontent.com/85419447/140407186-7c449636-eae9-46d7-a1ad-f9829537f21c.png">

2021-11-04 20:49 UTC, dvelezroman commented
the response might be :
 `{ success: true, body: { token: 'sdsdsds', ....otherProperties } }`

2021-11-04 21:31 UTC, dvelezroman approved these changes

2021-11-04 21:52 UTC, verteramofederico approved these changes

2021-11-05 19:27 UTC, dvelezroman approved these changes
Cool

2021-11-05 20:27 UTC, verteramofederico approved these changes

2021-11-09 00:06 UTC, andresmonsa approved these changes

2021-11-09 00:06 UTC, jpuery71292 approved these changes

2021-11-09 00:06 UTC, maxipaci approved these changes

2021-11-09 00:07 UTC, merged