OT90-702
alkemyTech/OT-90-server pull request #49
Opened 2021-11-05 17:26 UTC by andresmonsa

COMO usuario administrador
QUIERO eliminar testimonios
PARA moderar los testimonios y novedades acerca de la ONG.

Criterios de aceptación:
Cuando el usuario se registre en el sitio, deberá loguearse automáticamente y redirigirse a la ruta base(/).
 Para ello, es necesario **modificar el servidor para que devuelva el token una vez creado el usuario, y almacenar el mismo en el lado del cliente**

![image](https://user-images.githubusercontent.com/73470251/140552986-be88e94e-9b57-447a-87c8-ba0567d6a7a8.png)

2021-11-05 18:04 UTC, verteramofederico commented
groso! Puede ser que falte al final agregarle un redirect(/) ?

2021-11-05 18:04 UTC, verteramofederico approved these changes

2021-11-05 19:32 UTC, dvelezroman requested changes

2021-11-05 19:32 UTC, dvelezroman commented on components/user/network.js
> +      .then((response) => res.cookie('Authorization', `${response}`).status(201).send(response))
debe ser algo parecido al login... enviar en el cuerpo del response el token JWT ... junto con los datos del nuevo user...

2021-11-05 19:32 UTC, dvelezroman commented
> groso! Puede ser que falte al final agregarle un redirect(/) ?

lo de la redireccion iria en el cliente....

2021-11-05 22:17 UTC, andresmonsa commented
> groso! Puede ser que falte al final agregarle un redirect(/) ?

Tengo entendido que se hace en el front

2021-11-05 22:25 UTC, andresmonsa commented on components/user/network.js
> +      .then((response) => res.cookie('Authorization', `${response}`).status(201).send(response))
> debe ser algo parecido al login... enviar en el cuerpo del response el token JWT ... junto con los datos del nuevo user...

Fixed
![Uploading image.png…]()

2021-11-06 23:18 UTC, benjaminPla approved these changes

2021-11-08 12:27 UTC, maxipaci approved these changes

2021-11-09 00:03 UTC, dvelezroman approved these changes

2021-11-09 00:03 UTC, merged