OT90-674
alkemyTech/OT-90-server pull request #59
Opened 2021-11-11 20:47 UTC by marcelonieva7

COMO: Desarrollador
QUIERO: Vincular el listado de novedades con API
PARA: Mostrar el contenido dinámicamente

Criterios de aceptación: Vincular pantallas de listado y detalle con backend.

- Agregados los query params limit y order.
- Solución a la respuesta  para GET ALL (devulve los campos name, image y createdAt)
- Solución  a la respuesta  para GET ALL (devuelve solo las entries cuyo campo type sea news)
- Ambos requisitos del ticket 661 https://alkemy-labs.atlassian.net/browse/OT90-661

GET news/ con limit y sort
![news sort limit](https://user-images.githubusercontent.com/72712805/141365989-b239108a-c996-4836-bc6f-9efebf32af71.png)

GET news/ sin query params

![news sin sort limit](https://user-images.githubusercontent.com/72712805/141366143-492aebff-9866-482e-ab02-deff215d7108.png)

2021-11-11 20:53 UTC, andresmonsa approved these changes

2021-11-11 20:53 UTC, andresmonsa commented on components/news/network.js
>      res.status(500).json({ Error: 'Something has gone wrong' })
la respuesta debería tener el formato acordado 
{ success: false, 
body : zarasa }

2021-11-11 20:53 UTC, andresmonsa commented on components/news/network.js
>      res.status(200).json(news)
la respuesta debería tener el formato acordado 
{ success: true, 
body : zarasa }

2021-11-11 20:53 UTC, andresmonsa commented on components/news/store.js
> +  const options = {
nice!

2021-11-11 21:09 UTC, dvelezroman requested changes
formatear las responses

2021-11-11 23:44 UTC, verteramofederico approved these changes

2021-11-12 11:32 UTC, benjaminPla approved these changes

2021-11-12 14:41 UTC, dvelezroman approved these changes

2021-11-12 15:34 UTC, merged