OT90-736 (test/testimonials.js)
alkemyTech/OT-90-server pull request #67
Opened 2021-11-16 16:48 UTC by benjaminPla

Test: Endpoints /testimonials

COMO desarrollador
QUIERO disponer de tests de /testimonials
PARA asegurar la integridad y funcionamiento del proyecto

Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

--

1. Create test/testimonials.js
2. Test.

<img width="1280" alt="Screen Shot 2021-11-16 at 13 44 20" src="https://user-images.githubusercontent.com/85419447/142028590-bb104ddf-bb53-45c3-bf73-132d248ac26b.png">

_Missing PUT test, i'll await your comments if it is ok_

2021-11-16 23:10 UTC, dvelezroman requested changes
Los archivos de test deben tener la extension test... 

este archivo deberia llamarse asi :

testimonials.test.js

de ese modo el linter no hara problemas

2021-11-18 18:32 UTC, dvelezroman approved these changes
Seria bueno tener mas casos de assersiones.... pero esta bien

2021-11-19 17:40 UTC, andresmonsa approved these changes

2021-11-23 20:52 UTC, maxipaci approved these changes

2021-11-23 20:52 UTC, merged