OT90-697
alkemyTech/OT-90-server pull request #7
Opened 2021-10-26 14:57 UTC by andresmonsa

'Created model & migration  testimonials'

2021-10-26 15:19 UTC, benjaminPla requested changes
Nice work,
try to commit more times,
try to add a seeder.

2021-10-26 22:44 UTC, benjaminPla approved these changes
nice work!

2021-10-26 22:47 UTC, Francisco-Merchan approved these changes

2021-10-26 23:58 UTC, dvelezroman approved these changes

2021-10-27 01:01 UTC, marcelonieva7 approved these changes
Todo bien

2021-10-27 10:32 UTC, merged